/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu.h)                                                     */
/* BINDTOOL_HEADER_FILE_HASH(fb2bb8bef0d70e1b197768e50da651d5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pdu/pdu.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_pydoc.h>

void bind_pdu(py::module& m)
{


    py::module m_types = m.def_submodule("types");


    py::enum_<::gr::pdu::types::vector_type>(m_types, "vector_type")
        .value("byte_t", ::gr::pdu::types::byte_t)       // 0
        .value("float_t", ::gr::pdu::types::float_t)     // 1
        .value("complex_t", ::gr::pdu::types::complex_t) // 2
        .export_values();

    py::implicitly_convertible<int, ::gr::pdu::types::vector_type>();


    m.def("itemsize", &::gr::pdu::itemsize, py::arg("type"), D(itemsize));


    m.def("type_matches",
          &::gr::pdu::type_matches,
          py::arg("type"),
          py::arg("v"),
          D(type_matches));


    m.def("make_pdu_vector",
          &::gr::pdu::make_pdu_vector,
          py::arg("type"),
          py::arg("buf"),
          py::arg("items"),
          D(make_pdu_vector));


    m.def(
        "type_from_pmt", &::gr::pdu::type_from_pmt, py::arg("vector"), D(type_from_pmt));


    py::module m_ports = m.def_submodule("ports");


    m_ports.def("data", &::gr::pdu::ports::data, D(ports, data));


    m_ports.def("dict", &::gr::pdu::ports::dict, D(ports, dict));


    m_ports.def("emit", &::gr::pdu::ports::emit, D(ports, emit));


    m_ports.def("msg", &::gr::pdu::ports::msg, D(ports, msg));


    m_ports.def("pdus", &::gr::pdu::ports::pdus, D(ports, pdus));
}
